#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on trusty-mitaka."""

from basic_deployment import DesignateBasicDeployment

if __name__ == '__main__':
    deployment = DesignateBasicDeployment(
        series='trusty',
        openstack='cloud:trusty-mitaka',
        source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
