#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on trusty-liberty."""

from basic_deployment import DesignateBasicDeployment

if __name__ == '__main__':
    deployment = DesignateBasicDeployment(
        series='trusty',
        openstack='cloud:trusty-liberty',
        source='cloud:trusty-updates/liberty')
    deployment.run_tests()
