#!/bin/bash

# NOTE: relies on new charm publishing features

set -ex

owner=${1:-openstack-charmers-next}

echo "Publishing designate charm to charm store as $owner"

charm upload build/trusty/designate ~${owner}/designate
charm publish ~${owner}/designate
charm change-perm --set-read everyone ~${owner}/designate
